/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:df9a6544-9b5e-4fad-963c-38a0fb5228e1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_LE0jm1Ixg",
    "aws_user_pools_web_client_id": "7m0tiiakib9h20j36c9hsdk6km",
    "oauth": {}
};


export default awsmobile;
